#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later

import argparse
import sys

import mtt.application


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument("-p", "--prefix",
                        help="Installation prefix (for gsettings schema, themes, etc)",
                        metavar="[/, /usr]")
    parser.add_argument("-v", "--version", action="version", version="0.1")

    args = parser.parse_args()

    app = mtt.application.MagnifierTweaks()
    status = app.run(None)
    sys.exit(status)
